### ISSUE TITLE
Erika not working on XinaA15 iPhone 11 iOS 15.1!

### ISSUE THREAD

**Issue by thecynicalguyy** [Paisseon/Erika#14]
Erika is not working on XinaA15 iPhone 11 iOS 15.1! There are no settings being shown in the Settings app. Neither does anything happen when I try tapping the Bundle ID for a tweak in Sileo. Saily isn't working properly on my iPhone after jailbreak so could not install Erika through Saily to test. Please help :(

**Comment by Paisseon** [comment]
There are no preferences, so it is not supposed to show in settings. A previous version had that but it got removed recently (because it had no benefits vis-a-vis Choicy and would be extra work for me :p) But Erika seems to not work on Sileo+Xina. I hope to fix this at some point but can't research it due to not having a Xina-compatible device. Also, the gesture to activate is by tapping on the tweak icon, not the bundle ID (this is also a change, because the bundle ID is covered when a package is in the queue).

You could try the Violyn app, which uses the same backend as Erika just in an app format instead of tweak.
